name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
      - '.markdownlint.yml'
      - '.github/workflows/markdownlint.yml'
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.yml'
      - '.github/workflows/markdownlint.yml'

jobs:
  markdownlint:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install markdownlint-cli2
        run: |
          npm install -g markdownlint-cli2
      - name: Run markdownlint
        run: |
          markdownlint-cli2 "**/*.md" "!**/.git/**" "!**/.build/**" "!**/.swiftpm/**" "!**/.github/**" "!**/.vale/**"
